ChibiOS/RT: Scheduler
Scheduler
RT Kernel » Base Kernel Services
Detailed Description
This module provides the default portable scheduler code.
Macros
#define firstprio(rlp) ((rlp)->next->prio)
Returns the priority of the first thread on the given ready list.
#define currp ch.rlist.current
Current thread pointer access macro.
#define __CH_STRINGIFY(a) #a
Utility to make the parameter a quoted string.
Wakeup status codes
#define MSG_OK (msg_t)0
Normal wakeup message.
#define MSG_TIMEOUT (msg_t)-1
Wakeup caused by a timeout condition.
#define MSG_RESET (msg_t)-2
Wakeup caused by a reset condition.
Priority constants
#define NOPRIO (tprio_t)0
Ready list header priority.
#define IDLEPRIO (tprio_t)1
Idle priority.
#define LOWPRIO (tprio_t)2
Lowest priority.
#define NORMALPRIO (tprio_t)128
Normal priority.
#define HIGHPRIO (tprio_t)255
Highest priority.
Thread states
#define CH_STATE_READY (tstate_t)0
Waiting on the ready list.
#define CH_STATE_CURRENT (tstate_t)1
Currently running.
#define CH_STATE_WTSTART (tstate_t)2
Just created.
#define CH_STATE_SUSPENDED (tstate_t)3
Suspended state.
#define CH_STATE_QUEUED (tstate_t)4
On an I/O queue.
#define CH_STATE_WTSEM (tstate_t)5
On a semaphore.
#define CH_STATE_WTMTX (tstate_t)6
On a mutex.
#define CH_STATE_WTCOND (tstate_t)7
On a cond.variable.
#define CH_STATE_SLEEPING (tstate_t)8
Sleeping.
#define CH_STATE_WTEXIT (tstate_t)9
Waiting a thread.
#define CH_STATE_WTOREVT (tstate_t)10
One event.
#define CH_STATE_WTANDEVT (tstate_t)11
Several events.
#define CH_STATE_SNDMSGQ (tstate_t)12
Sending a message, in queue.
#define CH_STATE_SNDMSG (tstate_t)13
Sent a message, waiting answer.
#define CH_STATE_WTMSG (tstate_t)14
Waiting for a message.
#define CH_STATE_FINAL (tstate_t)15
Thread terminated.
#define CH_STATE_NAMES
Thread states as array of strings.
Thread flags and attributes
#define CH_FLAG_MODE_MASK (tmode_t)3U
Thread memory mode mask.
#define CH_FLAG_MODE_STATIC (tmode_t)0U
Static thread.
#define CH_FLAG_MODE_HEAP (tmode_t)1U
Thread allocated from a Memory Heap.
#define CH_FLAG_MODE_MPOOL (tmode_t)2U
Thread allocated from a Memory Pool.
#define CH_FLAG_TERMINATE (tmode_t)4U
Termination requested flag.
Typedefs
typedef uint32_t systime_t
Type of system time.
typedef struct ch_thread thread_t
Type of a thread structure.
typedef thread_t * thread_reference_t
Type of a thread reference.
typedef struct ch_threads_list threads_list_t
Type of a generic threads single link list, it works like a stack.
typedef struct ch_threads_queue threads_queue_t
Type of a generic threads bidirectional linked list header and element.
typedef struct ch_ready_list ready_list_t
Type of a ready list header.
typedef void(* vtfunc_t) (void *p)
Type of a Virtual Timer callback function.
typedef struct ch_virtual_timer virtual_timer_t
Type of a Virtual Timer structure.
typedef struct ch_virtual_timers_list virtual_timers_list_t
Type of virtual timers list header.
typedef struct ch_system_debug system_debug_t
Type of a system debug structure.
typedef struct ch_system ch_system_t
Type of system data structure.
Data Structures
struct ch_threads_list
Generic threads single link list, it works like a stack.
struct ch_threads_queue
Generic threads bidirectional linked list header and element.
struct ch_thread
Structure representing a thread.
struct ch_virtual_timer
Virtual Timer descriptor structure.
struct ch_virtual_timers_list
Virtual timers list header.
struct ch_system_debug
System debug data structure.
struct ch_system
System data structure.
Functions
void _scheduler_init (void)
Scheduler initialization.
void queue_prio_insert (thread_t *tp, threads_queue_t *tqp)
Inserts a thread into a priority ordered queue.
void queue_insert (thread_t *tp, threads_queue_t *tqp)
Inserts a thread into a queue.
thread_t * queue_fifo_remove (threads_queue_t *tqp)
Removes the first-out thread from a queue and returns it.
thread_t * queue_lifo_remove (threads_queue_t *tqp)
Removes the last-out thread from a queue and returns it.
thread_t * queue_dequeue (thread_t *tp)
Removes a thread from a queue and returns it.
void list_insert (thread_t *tp, threads_list_t *tlp)
Pushes a thread_t on top of a stack list.
thread_t * list_remove (threads_list_t *tlp)
Pops a thread from the top of a stack list and returns it.
thread_t * chSchReadyI (thread_t *tp)
Inserts a thread in the Ready List placing it behind its peers.
thread_t * chSchReadyAheadI (thread_t *tp)
Inserts a thread in the Ready List placing it ahead its peers.
void chSchGoSleepS (tstate_t newstate)
Puts the current thread to sleep into the specified state.
msg_t chSchGoSleepTimeoutS (tstate_t newstate, systime_t time)
Puts the current thread to sleep into the specified state with timeout specification.
void chSchWakeupS (thread_t *ntp, msg_t msg)
Wakes up a thread.
void chSchRescheduleS (void)
Performs a reschedule if a higher priority thread is runnable.
bool chSchIsPreemptionRequired (void)
Evaluates if preemption is required.
void chSchDoRescheduleBehind (void)
Switches to the first thread on the runnable queue.
void chSchDoRescheduleAhead (void)
Switches to the first thread on the runnable queue.
void chSchDoReschedule (void)
Switches to the first thread on the runnable queue.
static void list_init (threads_list_t *tlp)
Threads list initialization.
static bool list_isempty (threads_list_t *tlp)
Evaluates to true if the specified threads list is empty.
static bool list_notempty (threads_list_t *tlp)
Evaluates to true if the specified threads list is not empty.
static void queue_init (threads_queue_t *tqp)
Threads queue initialization.
static bool queue_isempty (const threads_queue_t *tqp)
Evaluates to true if the specified threads queue is empty.
static bool queue_notempty (const threads_queue_t *tqp)
Evaluates to true if the specified threads queue is not empty.
static bool chSchIsRescRequiredI (void)
Determines if the current thread must reschedule.
static bool chSchCanYieldS (void)
Determines if yielding is possible.
static void chSchDoYieldS (void)
Yields the time slot.
static void chSchPreemption (void)
Inline-able preemption code.
Variables
ch_system_t ch
System data structures.
Macro Definition Documentation
#define MSG_OK (msg_t)0
Normal wakeup message.
Definition at line 39 of file chschd.h.
Referenced by chCondSignal(), chCondSignalI(), chEvtSignalI(), chEvtWaitAllTimeout(), chEvtWaitAnyTimeout(), chEvtWaitOneTimeout(), chGuardedPoolAllocTimeoutS(), chMBFetchI(), chMBFetchS(), chMBPostAheadI(), chMBPostAheadS(), chMBPostI(), chMBPostS(), chSemAddCounterI(), chSemSignal(), chSemSignalI(), chSemSignalWait(), chSemWaitS(), chSemWaitTimeoutS(), chThdCreate(), chThdCreateFromHeap(), chThdCreateFromMemoryPool(), chThdCreateStatic(), and chThdStart().
#define MSG_TIMEOUT (msg_t)-1
Wakeup caused by a timeout condition.
Definition at line 40 of file chschd.h.
Referenced by chCondWaitTimeoutS(), chMBFetchI(), chMBPostAheadI(), chMBPostI(), chSchGoSleepS(), chSemWaitTimeoutS(), chThdEnqueueTimeoutS(), and chThdSuspendTimeoutS().
#define MSG_RESET (msg_t)-2
Wakeup caused by a reset condition.
Definition at line 43 of file chschd.h.
Referenced by chCondBroadcastI(), chMBFetchI(), chMBFetchS(), chMBPostAheadI(), chMBPostAheadS(), chMBPostI(), chMBPostS(), chMBResetI(), and chSemResetI().
#define NOPRIO (tprio_t)0
Ready list header priority.
Definition at line 52 of file chschd.h.
Referenced by _scheduler_init().
#define IDLEPRIO (tprio_t)1
Idle priority.
Definition at line 55 of file chschd.h.
Referenced by chSchDoReschedule(), chSchDoRescheduleAhead(), chSchDoRescheduleBehind(), chSchGoSleepS(), chSchWakeupS(), and chSysInit().
#define LOWPRIO (tprio_t)2
Lowest priority.
Definition at line 56 of file chschd.h.
#define NORMALPRIO (tprio_t)128
Normal priority.
Definition at line 57 of file chschd.h.
Referenced by chSysInit().
#define HIGHPRIO (tprio_t)255
Highest priority.
Definition at line 58 of file chschd.h.
Referenced by chThdCreateStatic(), chThdCreateSuspendedI(), and chThdSetPriority().
#define CH_STATE_READY (tstate_t)0
Waiting on the ready list.
Definition at line 65 of file chschd.h.
Referenced by chMtxLockS(), chSchGoSleepS(), chSchReadyAheadI(), and chSchReadyI().
#define CH_STATE_CURRENT (tstate_t)1
Currently running.
Definition at line 68 of file chschd.h.
Referenced by chMtxLockS(), chSchDoReschedule(), chSchDoRescheduleAhead(), chSchDoRescheduleBehind(), chSchGoSleepS(), chSchWakeupS(), and chSysInit().
#define CH_STATE_WTSTART (tstate_t)2
Just created.
Definition at line 69 of file chschd.h.
Referenced by _thread_init(), chThdStart(), and chThdStartI().
#define CH_STATE_SUSPENDED (tstate_t)3
Suspended state.
Definition at line 70 of file chschd.h.
Referenced by chSchGoSleepS(), chThdResumeI(), chThdResumeS(), chThdSuspendS(), and chThdSuspendTimeoutS().
#define CH_STATE_QUEUED (tstate_t)4
On an I/O queue.
Definition at line 71 of file chschd.h.
Referenced by chSchGoSleepS(), chThdDoDequeueNextI(), and chThdEnqueueTimeoutS().
#define CH_STATE_WTSEM (tstate_t)5
On a semaphore.
Definition at line 72 of file chschd.h.
Referenced by chMtxLockS(), chSchGoSleepS(), chSemSignalWait(), chSemWaitS(), and chSemWaitTimeoutS().
#define CH_STATE_WTMTX (tstate_t)6
On a mutex.
Definition at line 73 of file chschd.h.
Referenced by chMtxLockS().
#define CH_STATE_WTCOND (tstate_t)7
On a cond.variable.
Definition at line 74 of file chschd.h.
Referenced by chCondWaitS(), chCondWaitTimeoutS(), chMtxLockS(), and chSchGoSleepS().
#define CH_STATE_SLEEPING (tstate_t)8
Sleeping.
Definition at line 75 of file chschd.h.
Referenced by chThdSleepS().
#define CH_STATE_WTEXIT (tstate_t)9
Waiting a thread.
Definition at line 76 of file chschd.h.
Referenced by chThdWait().
#define CH_STATE_WTOREVT (tstate_t)10
One event.
Definition at line 77 of file chschd.h.
Referenced by chEvtSignalI(), chEvtWaitAny(), chEvtWaitAnyTimeout(), chEvtWaitOne(), and chEvtWaitOneTimeout().
#define CH_STATE_WTANDEVT (tstate_t)11
Several events.
Definition at line 78 of file chschd.h.
Referenced by chEvtSignalI(), chEvtWaitAll(), and chEvtWaitAllTimeout().
#define CH_STATE_SNDMSGQ (tstate_t)12
Sending a message, in queue.
Definition at line 79 of file chschd.h.
Referenced by chMsgSend(), and chMtxLockS().
#define CH_STATE_SNDMSG (tstate_t)13
Sent a message, waiting answer.
Definition at line 82 of file chschd.h.
Referenced by chMsgGet(), chMsgRelease(), and chMsgWait().
#define CH_STATE_WTMSG (tstate_t)14
Waiting for a message.
Definition at line 85 of file chschd.h.
Referenced by chMsgSend(), and chMsgWait().
#define CH_STATE_FINAL (tstate_t)15
Thread terminated.
Definition at line 88 of file chschd.h.
Referenced by chSchReadyAheadI(), chSchReadyI(), chThdExitS(), chThdRelease(), chThdTerminatedX(), and chThdWait().
#define CH_STATE_NAMES
Value:
"READY", "CURRENT", "WTSTART", "SUSPENDED", "QUEUED", "WTSEM", "WTMTX",  \
  "WTCOND", "SLEEPING", "WTEXIT", "WTOREVT", "WTANDEVT", "SNDMSGQ",        \
  "SNDMSG", "WTMSG", "FINAL"
Thread states as array of strings.
Each element in an array initialized with this macro can be indexed using the numeric thread state values.
Definition at line 95 of file chschd.h.
#define CH_FLAG_MODE_MASK (tmode_t)3U
Thread memory mode mask.
Definition at line 105 of file chschd.h.
Referenced by chThdExitS(), and chThdRelease().
#define CH_FLAG_MODE_STATIC (tmode_t)0U
Static thread.
Definition at line 108 of file chschd.h.
Referenced by _thread_init(), and chThdExitS().
#define CH_FLAG_MODE_HEAP (tmode_t)1U
Thread allocated from a Memory Heap.
Definition at line 109 of file chschd.h.
Referenced by chThdCreateFromHeap(), and chThdRelease().
#define CH_FLAG_MODE_MPOOL (tmode_t)2U
Thread allocated from a Memory Pool.
Definition at line 112 of file chschd.h.
Referenced by chThdCreateFromMemoryPool(), and chThdRelease().
#define CH_FLAG_TERMINATE (tmode_t)4U
Termination requested flag.
Definition at line 115 of file chschd.h.
Referenced by chThdShouldTerminateX(), and chThdTerminate().
#define firstprio (rlp) ((rlp)->next->prio)
Returns the priority of the first thread on the given ready list.
Function Class:
Not an API, this function is for internal use only.
Definition at line 463 of file chschd.h.
Referenced by chSchDoYieldS(), chSchIsPreemptionRequired(), chSchIsRescRequiredI(), and queue_notempty().
#define currp ch.rlist.current
Current thread pointer access macro.
Note
This macro is not meant to be used in the application code but only from within the kernel, use chThdGetSelfX() instead.
Definition at line 470 of file chschd.h.
Referenced by _trace_switch(), chCondWaitS(), chCondWaitTimeoutS(), chEvtAddEvents(), chEvtGetAndClearEvents(), chEvtGetEventsX(), chEvtRegisterMaskWithFlags(), chEvtWaitAll(), chEvtWaitAllTimeout(), chEvtWaitAny(), chEvtWaitAnyTimeout(), chEvtWaitOne(), chEvtWaitOneTimeout(), chMsgSend(), chMsgWait(), chMtxLockS(), chMtxTryLockS(), chMtxUnlock(), chMtxUnlockAll(), chMtxUnlockAllS(), chMtxUnlockS(), chSchDoReschedule(), chSchDoRescheduleAhead(), chSchDoRescheduleBehind(), chSchDoYieldS(), chSchGoSleepS(), chSchGoSleepTimeoutS(), chSchIsPreemptionRequired(), chSchIsRescRequiredI(), chSchWakeupS(), chSemSignalWait(), chSemWaitS(), chSemWaitTimeoutS(), chSysInit(), chSysTimerHandlerI(), chThdEnqueueTimeoutS(), chThdExitS(), chThdSetPriority(), chThdWait(), and queue_notempty().
#define __CH_STRINGIFY (a) #a
Utility to make the parameter a quoted string.
Definition at line 121 of file chsystypes.h.
Typedef Documentation
typedef uint32_t systime_t
Type of system time.
Definition at line 51 of file chsystypes.h.
typedef struct ch_thread thread_t
Type of a thread structure.
Definition at line 63 of file chsystypes.h.
typedef thread_t* thread_reference_t
Type of a thread reference.
Definition at line 68 of file chsystypes.h.
typedef struct ch_threads_list threads_list_t
Type of a generic threads single link list, it works like a stack.
Definition at line 73 of file chsystypes.h.
typedef struct ch_threads_queue threads_queue_t
Type of a generic threads bidirectional linked list header and element.
Definition at line 80 of file chsystypes.h.
typedef struct ch_ready_list ready_list_t
Type of a ready list header.
Definition at line 87 of file chsystypes.h.
typedef void(* vtfunc_t) (void *p)
Type of a Virtual Timer callback function.
Definition at line 92 of file chsystypes.h.
typedef struct ch_virtual_timer virtual_timer_t
Type of a Virtual Timer structure.
Definition at line 97 of file chsystypes.h.
typedef struct ch_virtual_timers_list virtual_timers_list_t
Type of virtual timers list header.
Definition at line 102 of file chsystypes.h.
typedef struct ch_system_debug system_debug_t
Type of a system debug structure.
Definition at line 107 of file chsystypes.h.
typedef struct ch_system ch_system_t
Type of system data structure.
Definition at line 112 of file chsystypes.h.
Function Documentation
void _scheduler_init (void)
Scheduler initialization.
Function Class:
Not an API, this function is for internal use only.
Definition at line 65 of file chschd.c.
References NOPRIO, queue_init(), and ch_system::rlist.
Referenced by chSysInit().
static void queue_prio_insert (thread_t * tp, threads_queue_t * tqp) inline
Inserts a thread into a priority ordered queue.
Note
The insertion is done by scanning the list from the highest priority toward the lowest.
Parameters
[in] tp the pointer to the thread to be inserted in the list
[in] tqp the pointer to the threads list header
Function Class:
Not an API, this function is for internal use only.
Definition at line 86 of file chschd.c.
References ch_threads_queue::next, ch_threads_queue::prev, ch_thread::prio, and ch_thread::queue.
Referenced by chCondWaitS(), chCondWaitTimeoutS(), chMtxLockS(), and queue_notempty().
static void queue_insert (thread_t * tp, threads_queue_t * tqp) inline
Inserts a thread into a queue.
Parameters
[in] tp the pointer to the thread to be inserted in the list
[in] tqp the pointer to the threads list header
Function Class:
Not an API, this function is for internal use only.
Definition at line 106 of file chschd.c.
References ch_threads_queue::next, ch_threads_queue::prev, and ch_thread::queue.
Referenced by chThdEnqueueTimeoutS(), and queue_notempty().
static thread_t * queue_fifo_remove (threads_queue_t * tqp) inline
Removes the first-out thread from a queue and returns it.
Note
If the queue is priority ordered then this function returns the thread with the highest priority.
Parameters
[in] tqp the pointer to the threads list header
Returns
The removed thread pointer.
Function Class:
Not an API, this function is for internal use only.
Definition at line 124 of file chschd.c.
References ch_threads_queue::next, ch_threads_queue::prev, and ch_thread::queue.
Referenced by chCondBroadcastI(), chCondSignal(), chCondSignalI(), chMsgWait(), chMtxUnlock(), chMtxUnlockAll(), chMtxUnlockAllS(), chMtxUnlockS(), chSchDoReschedule(), chSchDoRescheduleAhead(), chSchDoRescheduleBehind(), chSchGoSleepS(), chSemAddCounterI(), chSemSignal(), chSemSignalI(), chSemSignalWait(), chThdDoDequeueNextI(), and queue_notempty().
static thread_t * queue_lifo_remove (threads_queue_t * tqp) inline
Removes the last-out thread from a queue and returns it.
Note
If the queue is priority ordered then this function returns the thread with the lowest priority.
Parameters
[in] tqp the pointer to the threads list header
Returns
The removed thread pointer.
Function Class:
Not an API, this function is for internal use only.
Definition at line 143 of file chschd.c.
References ch_threads_queue::next, ch_threads_queue::prev, and ch_thread::queue.
Referenced by chSemResetI(), and queue_notempty().
static thread_t * queue_dequeue (thread_t * tp) inline
Removes a thread from a queue and returns it.
The thread is removed from the queue regardless of its relative position and regardless the used insertion method.
Parameters
[in] tp the pointer to the thread to be removed from the queue
Returns
The removed thread pointer.
Function Class:
Not an API, this function is for internal use only.
Definition at line 162 of file chschd.c.
References ch_threads_queue::next, ch_threads_queue::prev, and ch_thread::queue.
Referenced by chMtxLockS(), chSchGoSleepS(), and queue_notempty().
static void list_insert (thread_t * tp, threads_list_t * tlp) inline
Pushes a thread_t on top of a stack list.
Parameters
[in] tp the pointer to the thread to be inserted in the list
[in] tlp the pointer to the threads list header
Function Class:
Not an API, this function is for internal use only.
Definition at line 178 of file chschd.c.
References ch_threads_list::next, ch_threads_queue::next, and ch_thread::queue.
Referenced by chThdWait(), and queue_isempty().
static thread_t * list_remove (threads_list_t * tlp) inline
Pops a thread from the top of a stack list and returns it.
Precondition
The list must be non-empty before calling this function.
Parameters
[in] tlp the pointer to the threads list header
Returns
The removed thread pointer.
Function Class:
Not an API, this function is for internal use only.
Definition at line 193 of file chschd.c.
References ch_threads_list::next, ch_threads_queue::next, and ch_thread::queue.
Referenced by chThdExitS().
thread_t * chSchReadyI (thread_t * tp)
Inserts a thread in the Ready List placing it behind its peers.
The thread is positioned behind all threads with higher or equal priority.
Precondition
The thread must not be already inserted in any list through its next and prev or list corruption would occur.
Postcondition
This function does not reschedule so a call to a rescheduling function must be performed before unlocking the kernel. Note that interrupt handlers always reschedule on exit so an explicit reschedule must not be performed in ISRs.
Parameters
[in] tp the thread to be made ready
Returns
The thread pointer.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 218 of file chschd.c.
References CH_STATE_FINAL, CH_STATE_READY, chDbgAssert, chDbgCheck, chDbgCheckClassI(), ch_threads_queue::next, ch_thread::queue, ch_system::rlist, and ch_thread::state.
Referenced by chCondBroadcastI(), chCondSignalI(), chEvtSignalI(), chMsgSend(), chMtxLockS(), chMtxUnlock(), chMtxUnlockAll(), chMtxUnlockAllS(), chMtxUnlockS(), chSchDoReschedule(), chSchDoRescheduleBehind(), chSchGoSleepS(), chSchWakeupS(), chSemAddCounterI(), chSemResetI(), chSemSignalI(), chSemSignalWait(), chThdCreateI(), chThdDoDequeueNextI(), chThdExitS(), chThdResumeI(), and chThdStartI().
thread_t * chSchReadyAheadI (thread_t * tp)
Inserts a thread in the Ready List placing it ahead its peers.
The thread is positioned ahead all threads with higher or equal priority.
Precondition
The thread must not be already inserted in any list through its next and prev or list corruption would occur.
Postcondition
This function does not reschedule so a call to a rescheduling function must be performed before unlocking the kernel. Note that interrupt handlers always reschedule on exit so an explicit reschedule must not be performed in ISRs.
Parameters
[in] tp the thread to be made ready
Returns
The thread pointer.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 257 of file chschd.c.
References CH_STATE_FINAL, CH_STATE_READY, chDbgAssert, chDbgCheck, chDbgCheckClassI(), ch_threads_queue::next, ch_thread::queue, ch_system::rlist, and ch_thread::state.
Referenced by chSchDoReschedule(), and chSchDoRescheduleAhead().
void chSchGoSleepS (tstate_t newstate)
Puts the current thread to sleep into the specified state.
The thread goes into a sleeping state. The possible Thread States are defined into threads.h.
Parameters
[in] newstate the new thread state
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 289 of file chschd.c.
References CH_CFG_IDLE_ENTER_HOOK, CH_CFG_TIME_QUANTUM, CH_STATE_CURRENT, CH_STATE_QUEUED, CH_STATE_READY, CH_STATE_SUSPENDED, CH_STATE_WTCOND, CH_STATE_WTSEM, chDbgCheckClassS(), chSchReadyI(), chSemFastSignalI(), chSysLockFromISR(), chSysSwitch, chSysUnlockFromISR(), currp, IDLEPRIO, MSG_TIMEOUT, ch_thread::preempt, queue_dequeue(), queue_fifo_remove(), ch_thread::rdymsg, ch_system::rlist, ch_thread::state, ch_thread::u, ch_thread::wtsemp, and ch_thread::wttrp.
Referenced by chCondWaitS(), chEvtWaitAll(), chEvtWaitAny(), chEvtWaitOne(), chMsgSend(), chMsgWait(), chMtxLockS(), chSchGoSleepTimeoutS(), chSemSignalWait(), chSemWaitS(), chThdExitS(), chThdSuspendS(), and chThdWait().
msg_t chSchGoSleepTimeoutS (tstate_t newstate, systime_t time)
Puts the current thread to sleep into the specified state with timeout specification.
The thread goes into a sleeping state, if it is not awakened explicitly within the specified timeout then it is forcibly awakened with a MSG_TIMEOUT low level message. The possible Thread States are defined into threads.h.
Parameters
[in] newstate the new thread state
[in] time the number of ticks before the operation timeouts, the special values are handled as follow:
TIME_INFINITE the thread enters an infinite sleep state, this is equivalent to invoking chSchGoSleepS() but, of course, less efficient.
TIME_IMMEDIATE this value is not allowed.
Returns
The wakeup message.
Return values
MSG_TIMEOUT if a timeout occurs.
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 375 of file chschd.c.
References chDbgCheckClassS(), chSchGoSleepS(), chVTDoResetI(), chVTDoSetI(), chVTIsArmedI(), currp, and TIME_INFINITE.
Referenced by chCondWaitTimeoutS(), chEvtWaitAllTimeout(), chEvtWaitAnyTimeout(), chEvtWaitOneTimeout(), chSemWaitTimeoutS(), chThdEnqueueTimeoutS(), chThdSleepS(), and chThdSuspendTimeoutS().
void chSchWakeupS (thread_t * ntp, msg_t msg)
Wakes up a thread.
The thread is inserted into the ready list or immediately made running depending on its relative priority compared to the current thread.
Precondition
The thread must not be already inserted in any list through its next and prev or list corruption would occur.
Note
It is equivalent to a chSchReadyI() followed by a chSchRescheduleS() but much more efficient.
The function assumes that the current thread has the highest priority.
Parameters
[in] ntp the thread to be made ready
[in] msg the wakeup message
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 412 of file chschd.c.
References CH_CFG_IDLE_LEAVE_HOOK, CH_STATE_CURRENT, chDbgAssert, chDbgCheckClassS(), chSchReadyI(), chSysSwitch, currp, IDLEPRIO, ch_thread::prio, ch_thread::rdymsg, ch_system::rlist, ch_thread::state, and ch_thread::u.
Referenced by chCondSignal(), chMsgReleaseS(), chSemSignal(), chThdCreate(), chThdCreateFromHeap(), chThdCreateFromMemoryPool(), chThdCreateStatic(), chThdResumeS(), and chThdStart().
void chSchRescheduleS (void)
Performs a reschedule if a higher priority thread is runnable.
If a thread with a higher priority than the current thread is in the ready list then make the higher priority thread running.
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 456 of file chschd.c.
References chDbgCheckClassS(), chSchDoRescheduleAhead(), and chSchIsRescRequiredI().
Referenced by chBSemSignal(), chCondBroadcast(), chEvtBroadcastFlags(), chEvtSignal(), chGuardedPoolFree(), chMBFetchS(), chMBPostAheadS(), chMBPostS(), chMBReset(), chMtxUnlock(), chMtxUnlockAll(), chSemReset(), chSemSignalWait(), chSysRestoreStatusX(), and chThdSetPriority().
bool chSchIsPreemptionRequired (void)
Evaluates if preemption is required.
The decision is taken by comparing the relative priorities and depending on the state of the round robin timeout counter.
Note
Not a user function, it is meant to be invoked by the scheduler itself or from within the port layer.
Return values
true if there is a thread that must go in running state immediately.
false if preemption is not required.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 478 of file chschd.c.
References currp, firstprio, and ch_system::rlist.
void chSchDoRescheduleBehind (void)
Switches to the first thread on the runnable queue.
The current thread is positioned in the ready list behind all threads having the same priority. The thread regains its time quantum.
Note
Not a user function, it is meant to be invoked by the scheduler itself.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 505 of file chschd.c.
References CH_CFG_IDLE_LEAVE_HOOK, CH_CFG_TIME_QUANTUM, CH_STATE_CURRENT, chSchReadyI(), chSysSwitch, currp, IDLEPRIO, ch_thread::preempt, ch_thread::prio, queue_fifo_remove(), and ch_system::rlist.
Referenced by chSchCanYieldS(), and chSchPreemption().
void chSchDoRescheduleAhead (void)
Switches to the first thread on the runnable queue.
The current thread is positioned in the ready list ahead of all threads having the same priority.
Note
Not a user function, it is meant to be invoked by the scheduler itself.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 538 of file chschd.c.
References CH_CFG_IDLE_LEAVE_HOOK, CH_STATE_CURRENT, chSchReadyAheadI(), chSysSwitch, currp, IDLEPRIO, ch_thread::prio, queue_fifo_remove(), and ch_system::rlist.
Referenced by chSchDoYieldS(), chSchPreemption(), and chSchRescheduleS().
void chSchDoReschedule (void)
Switches to the first thread on the runnable queue.
The current thread is positioned in the ready list behind or ahead of all threads having the same priority depending on if it used its whole time slice.
Note
Not a user function, it is meant to be invoked by the scheduler itself or from within the port layer.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 567 of file chschd.c.
References CH_CFG_IDLE_LEAVE_HOOK, CH_CFG_TIME_QUANTUM, CH_STATE_CURRENT, chSchReadyAheadI(), chSchReadyI(), chSysSwitch, currp, IDLEPRIO, ch_thread::preempt, ch_thread::prio, queue_fifo_remove(), and ch_system::rlist.
static void list_init (threads_list_t * tlp) inline static
Threads list initialization.
Parameters
[in] tlp pointer to the threads list object
Function Class:
Not an API, this function is for internal use only.
Definition at line 521 of file chschd.h.
References ch_threads_list::next.
Referenced by _thread_init().
static bool list_isempty (threads_list_t * tlp) inline static
Evaluates to true if the specified threads list is empty.
Parameters
[in] tlp pointer to the threads list object
Returns
The status of the list.
Function Class:
Not an API, this function is for internal use only.
Definition at line 534 of file chschd.h.
References ch_threads_list::next.
static bool list_notempty (threads_list_t * tlp) inline static
Evaluates to true if the specified threads list is not empty.
Parameters
[in] tlp pointer to the threads list object
Returns
The status of the list.
Function Class:
Not an API, this function is for internal use only.
Definition at line 547 of file chschd.h.
References ch_threads_queue::next, and ch_threads_queue::prev.
Referenced by chThdExitS().
static void queue_init (threads_queue_t * tqp) inline static
Threads queue initialization.
Parameters
[in] tqp pointer to the threads queue object
Function Class:
Not an API, this function is for internal use only.
Definition at line 559 of file chschd.h.
References ch_threads_queue::next.
Referenced by _scheduler_init(), _thread_init(), chCondObjectInit(), chMtxObjectInit(), chSemObjectInit(), and chThdQueueObjectInit().
static bool queue_isempty (const threads_queue_t * tqp) inline static
Evaluates to true if the specified threads queue is empty.
Parameters
[in] tqp pointer to the threads queue object
Returns
The status of the queue.
Function Class:
Not an API, this function is for internal use only.
Definition at line 573 of file chschd.h.
References list_insert(), ch_threads_list::next, ch_threads_queue::next, and ch_thread::queue.
Referenced by chSemAddCounterI(), chSemResetI(), chSemSignal(), chSemSignalI(), chSemSignalWait(), chSemWaitS(), chSemWaitTimeoutS(), and chThdQueueIsEmptyI().
static bool queue_notempty (const threads_queue_t * tqp) inline static
Evaluates to true if the specified threads queue is not empty.
Parameters
[in] tqp pointer to the threads queue object
Returns
The status of the queue.
Function Class:
Not an API, this function is for internal use only.
Definition at line 586 of file chschd.h.
References chDbgCheckClassI(), chSchIsRescRequiredI(), currp, firstprio, ch_threads_list::next, ch_threads_queue::next, ch_threads_queue::prev, ch_thread::prio, ch_thread::queue, queue_dequeue(), queue_fifo_remove(), queue_insert(), queue_lifo_remove(), queue_prio_insert(), and ch_system::rlist.
Referenced by chCondBroadcastI(), chCondSignal(), chCondSignalI(), chMtxQueueNotEmptyS(), chSemAddCounterI(), chSemResetI(), chSemSignal(), chSemSignalI(), chSemSignalWait(), chSemWaitS(), chSemWaitTimeoutS(), chThdDequeueAllI(), chThdDequeueNextI(), and chThdDoDequeueNextI().
static bool chSchIsRescRequiredI (void) inline static
Determines if the current thread must reschedule.
This function returns true if there is a ready thread with higher priority.
Returns
The priorities situation.
Return values
false if rescheduling is not necessary.
true if there is a ready thread at higher priority.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 666 of file chschd.h.
References chDbgCheckClassS(), currp, firstprio, and ch_system::rlist.
Referenced by chSchRescheduleS(), and queue_notempty().
static bool chSchCanYieldS (void) inline static
Determines if yielding is possible.
This function returns true if there is a ready thread with equal or higher priority.
Returns
The priorities situation.
Return values
false if yielding is not possible.
true if there is a ready thread at equal or higher priority.
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 684 of file chschd.h.
References chDbgCheckClassS(), and chSchDoRescheduleBehind().
static void chSchDoYieldS (void) inline static
Yields the time slot.
Yields the CPU control to the next thread in the ready list with equal or higher priority, if any.
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 698 of file chschd.h.
References chSchDoRescheduleAhead(), currp, firstprio, and ch_system::rlist.
Referenced by chThdYield().
static void chSchPreemption (void) inline static
Inline-able preemption code.
This is the common preemption code, this function must be invoked exclusively from the port layer.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 714 of file chschd.h.
References chSchDoRescheduleAhead(), and chSchDoRescheduleBehind().
Variable Documentation
ch_system_t ch
System data structures.
Definition at line 42 of file chschd.c.
Referenced by _dbg_check_disable(), _dbg_check_enable(), _dbg_check_enter_isr(), _dbg_check_leave_isr(), _dbg_check_lock(), _dbg_check_lock_from_isr(), _dbg_check_suspend(), _dbg_check_unlock(), _dbg_check_unlock_from_isr(), _stats_ctxswc(), _stats_increase_irq(), _stats_init(), _stats_start_measure_crit_isr(), _stats_start_measure_crit_thd(), _stats_stop_measure_crit_isr(), _stats_stop_measure_crit_thd(), _tm_init(), _trace_halt(), _trace_init(), _trace_isr_enter(), _trace_isr_leave(), _trace_switch(), _vt_init(), chDbgCheckClassI(), chDbgCheckClassS(), chDbgResumeTraceI(), chDbgSuspendTraceI(), chDbgWriteTraceI(), chRegFirstThread(), chRegNextThread(), chRegSetThreadName(), chSysGetIdleThreadX(), chSysHalt(), chSysInit(), chSysIntegrityCheckI(), chSysUnlock(), chThdGetSelfX(), chTMStopMeasurementX(), chVTDoResetI(), chVTDoSetI(), chVTDoTickI(), chVTGetSystemTimeX(), chVTGetTimersStateI(), and trace_next().