ChibiOS/RT: Time and Virtual Timers
Time and Virtual Timers
RT Kernel » Base Kernel Services
Detailed Description
Time and Virtual Timers related APIs and services.
Macros
#define __UINT_MAX ((unsigned int)-1)
Maximum unsigned integer.
Special time constants
#define TIME_IMMEDIATE ((systime_t)0)
Zero time specification for some functions with a timeout specification.
#define TIME_INFINITE ((systime_t)-1)
Infinite time specification for all functions with a timeout specification.
#define TIME_MAXIMUM ((systime_t)-2)
Maximum time constant.
Fast time conversion utilities
#define S2ST(sec) ((systime_t)((uint32_t)(sec) * (uint32_t)CH_CFG_ST_FREQUENCY))
Seconds to system ticks.
#define MS2ST(msec)
Milliseconds to system ticks.
#define US2ST(usec)
Microseconds to system ticks.
#define ST2S(n) (((n) + CH_CFG_ST_FREQUENCY - 1UL) / CH_CFG_ST_FREQUENCY)
System ticks to seconds.
#define ST2MS(n)
System ticks to milliseconds.
#define ST2US(n)
System ticks to microseconds.
Secure time conversion utilities
static systime_t LL_S2ST (unsigned int sec)
Seconds to system ticks.
static systime_t LL_MS2ST (unsigned int msec)
Milliseconds to system ticks.
static systime_t LL_US2ST (unsigned int usec)
Microseconds to system ticks.
static unsigned int LL_ST2S (systime_t n)
System ticks to seconds.
static unsigned int LL_ST2MS (systime_t n)
System ticks to milliseconds.
static unsigned int LL_ST2US (systime_t n)
System ticks to microseconds.
Functions
void _vt_init (void)
Virtual Timers initialization.
void chVTDoSetI (virtual_timer_t *vtp, systime_t delay, vtfunc_t vtfunc, void *par)
Enables a virtual timer.
void chVTDoResetI (virtual_timer_t *vtp)
Disables a Virtual Timer.
static void chVTObjectInit (virtual_timer_t *vtp)
Initializes a virtual_timer_t object.
static systime_t chVTGetSystemTimeX (void)
Current system time.
static systime_t chVTGetSystemTime (void)
Current system time.
static systime_t chVTTimeElapsedSinceX (systime_t start)
Returns the elapsed time since the specified start time.
static bool chVTIsTimeWithinX (systime_t time, systime_t start, systime_t end)
Checks if the specified time is within the specified time window.
static bool chVTIsSystemTimeWithinX (systime_t start, systime_t end)
Checks if the current system time is within the specified time window.
static bool chVTIsSystemTimeWithin (systime_t start, systime_t end)
Checks if the current system time is within the specified time window.
static bool chVTGetTimersStateI (systime_t *timep)
Returns the time interval until the next timer event.
static bool chVTIsArmedI (virtual_timer_t *vtp)
Returns true if the specified timer is armed.
static bool chVTIsArmed (virtual_timer_t *vtp)
Returns true if the specified timer is armed.
static void chVTResetI (virtual_timer_t *vtp)
Disables a Virtual Timer.
static void chVTReset (virtual_timer_t *vtp)
Disables a Virtual Timer.
static void chVTSetI (virtual_timer_t *vtp, systime_t delay, vtfunc_t vtfunc, void *par)
Enables a virtual timer.
static void chVTSet (virtual_timer_t *vtp, systime_t delay, vtfunc_t vtfunc, void *par)
Enables a virtual timer.
static void chVTDoTickI (void)
Virtual timers ticker.
Macro Definition Documentation
#define TIME_IMMEDIATE ((systime_t)0)
Zero time specification for some functions with a timeout specification.
Note
Not all functions accept TIME_IMMEDIATE as timeout parameter, see the specific function documentation.
Definition at line 45 of file chvt.h.
Referenced by chCondWaitTimeoutS(), chEvtWaitAllTimeout(), chEvtWaitAnyTimeout(), chEvtWaitOneTimeout(), chSemWaitTimeoutS(), chThdEnqueueTimeoutS(), chThdSleepS(), chThdSuspendTimeoutS(), and chVTDoSetI().
#define TIME_INFINITE ((systime_t)-1)
Infinite time specification for all functions with a timeout specification.
Note
Not all functions accept TIME_INFINITE as timeout parameter, see the specific function documentation.
Definition at line 53 of file chvt.h.
Referenced by chSchGoSleepTimeoutS().
#define TIME_MAXIMUM ((systime_t)-2)
Maximum time constant.
Definition at line 58 of file chvt.h.
Referenced by LL_MS2ST(), LL_S2ST(), and LL_US2ST().
#define __UINT_MAX ((unsigned int)-1)
Maximum unsigned integer.
Definition at line 64 of file chvt.h.
Referenced by LL_ST2MS(), LL_ST2S(), and LL_ST2US().
#define S2ST (sec) ((systime_t)((uint32_t)(sec) * (uint32_t)CH_CFG_ST_FREQUENCY))
Seconds to system ticks.
Converts from seconds to system ticks number.
Note
The result is rounded upward to the next tick boundary.
Use of this macro for large values is not secure because integer overflows, make sure your value can be correctly converted.
Parameters
[in] sec number of seconds
Returns
The number of ticks.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 120 of file chvt.h.
#define MS2ST (msec)
Value:
((systime_t)(((((uint32_t)(msec)) *                                       \
                 ((uint32_t)CH_CFG_ST_FREQUENCY)) + 999UL) / 1000UL))
Milliseconds to system ticks.
Converts from milliseconds to system ticks number.
Note
The result is rounded upward to the next tick boundary.
Use of this macro for large values is not secure because integer overflows, make sure your value can be correctly converted.
Parameters
[in] msec number of milliseconds
Returns
The number of ticks.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 136 of file chvt.h.
#define US2ST (usec)
Value:
((systime_t)(((((uint32_t)(usec)) *                                       \
                 ((uint32_t)CH_CFG_ST_FREQUENCY)) + 999999UL) / 1000000UL))
Microseconds to system ticks.
Converts from microseconds to system ticks number.
Note
The result is rounded upward to the next tick boundary.
Use of this macro for large values is not secure because integer overflows, make sure your value can be correctly converted.
Parameters
[in] usec number of microseconds
Returns
The number of ticks.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 153 of file chvt.h.
#define ST2S (n) (((n) + CH_CFG_ST_FREQUENCY - 1UL) / CH_CFG_ST_FREQUENCY)
System ticks to seconds.
Converts from system ticks number to seconds.
Note
The result is rounded up to the next second boundary.
Use of this macro for large values is not secure because integer overflows, make sure your value can be correctly converted.
Parameters
[in] n number of system ticks
Returns
The number of seconds.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 170 of file chvt.h.
#define ST2MS (n)
Value:
(((n) * 1000UL + CH_CFG_ST_FREQUENCY - 1UL) /              \
                  CH_CFG_ST_FREQUENCY)
System ticks to milliseconds.
Converts from system ticks number to milliseconds.
Note
The result is rounded up to the next millisecond boundary.
Use of this macro for large values is not secure because integer overflows, make sure your value can be correctly converted.
Parameters
[in] n number of system ticks
Returns
The number of milliseconds.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 185 of file chvt.h.
#define ST2US (n)
Value:
(((n) * 1000000UL + CH_CFG_ST_FREQUENCY - 1UL) /           \
                  CH_CFG_ST_FREQUENCY)
System ticks to microseconds.
Converts from system ticks number to microseconds.
Note
The result is rounded up to the next microsecond boundary.
Use of this macro for large values is not secure because integer overflows, make sure your value can be correctly converted.
Parameters
[in] n number of system ticks
Returns
The number of microseconds.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 201 of file chvt.h.
Function Documentation
void _vt_init (void)
Virtual Timers initialization.
Note
Internal use only.
Function Class:
Not an API, this function is for internal use only.
Definition at line 61 of file chvt.c.
References ch, ch_virtual_timers_list::delta, ch_virtual_timers_list::lasttime, ch_virtual_timers_list::next, ch_virtual_timers_list::prev, ch_virtual_timers_list::systime, and ch_system::vtlist.
Referenced by chSysInit().
void chVTDoSetI (virtual_timer_t * vtp, systime_t delay, vtfunc_t vtfunc, void * par)
Enables a virtual timer.
The timer is enabled and programmed to trigger after the delay specified as parameter.
Precondition
The timer must not be already armed before calling this function.
Note
The callback function is invoked from interrupt context.
Parameters
[out] vtp the virtual_timer_t structure pointer
[in] delay the number of ticks before the operation timeouts, the special values are handled as follow:
TIME_INFINITE is allowed but interpreted as a normal time specification.
TIME_IMMEDIATE this value is not allowed.
[in] vtfunc the timer callback function. After invoking the callback the timer is disabled and the structure can be disposed or reused.
[in] par a parameter that will be passed to the callback function
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 95 of file chvt.c.
References ch, CH_CFG_ST_TIMEDELTA, chDbgAssert, chDbgCheck, chDbgCheckClassI(), chVTGetSystemTimeX(), ch_virtual_timer::delta, ch_virtual_timers_list::delta, ch_virtual_timer::func, ch_virtual_timers_list::lasttime, ch_virtual_timer::next, ch_virtual_timers_list::next, ch_virtual_timer::par, ch_virtual_timer::prev, ch_virtual_timers_list::prev, TIME_IMMEDIATE, and ch_system::vtlist.
Referenced by chSchGoSleepTimeoutS(), and chVTSetI().
void chVTDoResetI (virtual_timer_t * vtp)
Disables a Virtual Timer.
Precondition
The timer must be in armed state before calling this function.
Parameters
[in] vtp the virtual_timer_t structure pointer
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 195 of file chvt.c.
References ch, CH_CFG_ST_TIMEDELTA, chDbgAssert, chDbgCheck, chDbgCheckClassI(), chVTGetSystemTimeX(), ch_virtual_timer::delta, ch_virtual_timers_list::delta, ch_virtual_timer::func, ch_virtual_timers_list::lasttime, ch_virtual_timer::next, ch_virtual_timers_list::next, ch_virtual_timer::prev, and ch_system::vtlist.
Referenced by chSchGoSleepTimeoutS(), and chVTResetI().
static systime_t LL_S2ST (unsigned int sec) inline static
Seconds to system ticks.
Converts from seconds to system ticks number.
Note
The result is rounded upward to the next tick boundary.
This function uses a 64 bits internal representation, use with non-constant parameters can lead to inefficient code because 64 bits arithmetic would be used at runtime.
Parameters
[in] sec number of seconds
Returns
The number of ticks.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 244 of file chvt.h.
References CH_CFG_ST_FREQUENCY, chDbgAssert, and TIME_MAXIMUM.
static systime_t LL_MS2ST (unsigned int msec) inline static
Milliseconds to system ticks.
Converts from milliseconds to system ticks number.
Note
The result is rounded upward to the next tick boundary.
This function uses a 64 bits internal representation, use with non-constant parameters can lead to inefficient code because 64 bits arithmetic would be used at runtime.
Parameters
[in] msec number of milliseconds
Returns
The number of ticks.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 265 of file chvt.h.
References CH_CFG_ST_FREQUENCY, chDbgAssert, and TIME_MAXIMUM.
static systime_t LL_US2ST (unsigned int usec) inline static
Microseconds to system ticks.
Converts from microseconds to system ticks number.
Note
The result is rounded upward to the next tick boundary.
This function uses a 64 bits internal representation, use with non-constant parameters can lead to inefficient code because 64 bits arithmetic would be used at runtime.
Parameters
[in] usec number of microseconds
Returns
The number of ticks.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 287 of file chvt.h.
References CH_CFG_ST_FREQUENCY, chDbgAssert, and TIME_MAXIMUM.
static unsigned int LL_ST2S (systime_t n) inline static
System ticks to seconds.
Converts from system ticks number to seconds.
Note
The result is rounded up to the next second boundary.
This function uses a 64 bits internal representation, use with non-constant parameters can lead to inefficient code because 64 bits arithmetic would be used at runtime.
Parameters
[in] n number of system ticks
Returns
The number of seconds.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 309 of file chvt.h.
References __UINT_MAX, CH_CFG_ST_FREQUENCY, and chDbgAssert.
static unsigned int LL_ST2MS (systime_t n) inline static
System ticks to milliseconds.
Converts from system ticks number to milliseconds.
Note
The result is rounded up to the next millisecond boundary.
This function uses a 64 bits internal representation, use with non-constant parameters can lead to inefficient code because 64 bits arithmetic would be used at runtime.
Parameters
[in] n number of system ticks
Returns
The number of milliseconds.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 331 of file chvt.h.
References __UINT_MAX, CH_CFG_ST_FREQUENCY, and chDbgAssert.
static unsigned int LL_ST2US (systime_t n) inline static
System ticks to microseconds.
Converts from system ticks number to microseconds.
Note
The result is rounded up to the next microsecond boundary.
This function uses a 64 bits internal representation, use with non-constant parameters can lead to inefficient code because 64 bits arithmetic would be used at runtime.
Parameters
[in] n number of system ticks
Returns
The number of microseconds.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 353 of file chvt.h.
References __UINT_MAX, CH_CFG_ST_FREQUENCY, and chDbgAssert.
static void chVTObjectInit (virtual_timer_t * vtp) inline static
Initializes a virtual_timer_t object.
Note
Initializing a timer object is not strictly required because the function chVTSetI() initializes the object too. This function is only useful if you need to perform a chVTIsArmed() check before calling chVTSetI().
Parameters
[out] vtp the virtual_timer_t structure pointer
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 374 of file chvt.h.
References ch_virtual_timer::func.
static systime_t chVTGetSystemTimeX (void) inline static
Current system time.
Returns the number of system ticks since the chSysInit() invocation.
Note
The counter can reach its maximum and then restart from zero.
This function can be called from any context but its atomicity is not guaranteed on architectures whose word size is less than systime_t size.
Returns
The system time in ticks.
Function Class:
This is an X-Class API, this function can be invoked from any context.
Definition at line 392 of file chvt.h.
References ch, ch_virtual_timers_list::systime, and ch_system::vtlist.
Referenced by chThdSleepUntil(), chThdSleepUntilWindowed(), chVTDoResetI(), chVTDoSetI(), chVTDoTickI(), chVTGetSystemTime(), chVTGetTimersStateI(), chVTIsSystemTimeWithinX(), chVTTimeElapsedSinceX(), and trace_next().
static systime_t chVTGetSystemTime (void) inline static
Current system time.
Returns the number of system ticks since the chSysInit() invocation.
Note
The counter can reach its maximum and then restart from zero.
Returns
The system time in ticks.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 411 of file chvt.h.
References chSysLock(), chSysUnlock(), and chVTGetSystemTimeX().
Referenced by chVTIsSystemTimeWithin().
static systime_t chVTTimeElapsedSinceX (systime_t start) inline static
Returns the elapsed time since the specified start time.
Parameters
[in] start start time
Returns
The elapsed time.
Function Class:
This is an X-Class API, this function can be invoked from any context.
Definition at line 429 of file chvt.h.
References chVTGetSystemTimeX().
static bool chVTIsTimeWithinX (systime_t time, systime_t start, systime_t end) inline static
Checks if the specified time is within the specified time window.
Note
When start==end then the function returns always true because the whole time range is specified.
This function can be called from any context.
Parameters
[in] time the time to be verified
[in] start the start of the time window (inclusive)
[in] end the end of the time window (non inclusive)
Return values
true current time within the specified time window.
false current time not within the specified time window.
Function Class:
This is an X-Class API, this function can be invoked from any context.
Definition at line 448 of file chvt.h.
Referenced by chThdSleepUntilWindowed(), chVTIsSystemTimeWithin(), and chVTIsSystemTimeWithinX().
static bool chVTIsSystemTimeWithinX (systime_t start, systime_t end) inline static
Checks if the current system time is within the specified time window.
Note
When start==end then the function returns always true because the whole time range is specified.
Parameters
[in] start the start of the time window (inclusive)
[in] end the end of the time window (non inclusive)
Return values
true current time within the specified time window.
false current time not within the specified time window.
Function Class:
This is an X-Class API, this function can be invoked from any context.
Definition at line 468 of file chvt.h.
References chVTGetSystemTimeX(), and chVTIsTimeWithinX().
static bool chVTIsSystemTimeWithin (systime_t start, systime_t end) inline static
Checks if the current system time is within the specified time window.
Note
When start==end then the function returns always true because the whole time range is specified.
Parameters
[in] start the start of the time window (inclusive)
[in] end the end of the time window (non inclusive)
Return values
true current time within the specified time window.
false current time not within the specified time window.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 486 of file chvt.h.
References chVTGetSystemTime(), and chVTIsTimeWithinX().
static bool chVTGetTimersStateI (systime_t * timep) inline static
Returns the time interval until the next timer event.
Note
The return value is not perfectly accurate and can report values in excess of CH_CFG_ST_TIMEDELTA ticks.
The interval returned by this function is only meaningful if more timers are not added to the list until the returned time.
Parameters
[out] timep pointer to a variable that will contain the time interval until the next timer elapses. This pointer can be NULL if the information is not required.
Returns
The time, in ticks, until next time event.
Return values
false if the timers list is empty.
true if the timers list contains at least one timer.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 507 of file chvt.h.
References ch, CH_CFG_ST_TIMEDELTA, chDbgCheckClassI(), chVTGetSystemTimeX(), ch_virtual_timer::delta, ch_virtual_timers_list::lasttime, ch_virtual_timers_list::next, and ch_system::vtlist.
static bool chVTIsArmedI (virtual_timer_t * vtp) inline static
Returns true if the specified timer is armed.
Precondition
The timer must have been initialized using chVTObjectInit() or chVTDoSetI().
Parameters
[in] vtp the virtual_timer_t structure pointer
Returns
true if the timer is armed.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 537 of file chvt.h.
References chDbgCheckClassI(), and ch_virtual_timer::func.
Referenced by chSchGoSleepTimeoutS(), chVTIsArmed(), and chVTResetI().
static bool chVTIsArmed (virtual_timer_t * vtp) inline static
Returns true if the specified timer is armed.
Precondition
The timer must have been initialized using chVTObjectInit() or chVTDoSetI().
Parameters
[in] vtp the virtual_timer_t structure pointer
Returns
true if the timer is armed.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 554 of file chvt.h.
References chSysLock(), chSysUnlock(), and chVTIsArmedI().
static void chVTResetI (virtual_timer_t * vtp) inline static
Disables a Virtual Timer.
Note
The timer is first checked and disabled only if armed.
Precondition
The timer must have been initialized using chVTObjectInit() or chVTDoSetI().
Parameters
[in] vtp the virtual_timer_t structure pointer
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 574 of file chvt.h.
References chVTDoResetI(), and chVTIsArmedI().
Referenced by chVTReset(), and chVTSetI().
static void chVTReset (virtual_timer_t * vtp) inline static
Disables a Virtual Timer.
Note
The timer is first checked and disabled only if armed.
Precondition
The timer must have been initialized using chVTObjectInit() or chVTDoSetI().
Parameters
[in] vtp the virtual_timer_t structure pointer
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 591 of file chvt.h.
References chSysLock(), chSysUnlock(), and chVTResetI().
static void chVTSetI (virtual_timer_t * vtp, systime_t delay, vtfunc_t vtfunc, void * par) inline static
Enables a virtual timer.
If the virtual timer was already enabled then it is re-enabled using the new parameters.
Precondition
The timer must have been initialized using chVTObjectInit() or chVTDoSetI().
Parameters
[in] vtp the virtual_timer_t structure pointer
[in] delay the number of ticks before the operation timeouts, the special values are handled as follow:
TIME_INFINITE is allowed but interpreted as a normal time specification.
TIME_IMMEDIATE this value is not allowed.
[in] vtfunc the timer callback function. After invoking the callback the timer is disabled and the structure can be disposed or reused.
[in] par a parameter that will be passed to the callback function
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 620 of file chvt.h.
References chVTDoSetI(), and chVTResetI().
Referenced by chVTSet().
static void chVTSet (virtual_timer_t * vtp, systime_t delay, vtfunc_t vtfunc, void * par) inline static
Enables a virtual timer.
If the virtual timer was already enabled then it is re-enabled using the new parameters.
Precondition
The timer must have been initialized using chVTObjectInit() or chVTDoSetI().
Parameters
[in] vtp the virtual_timer_t structure pointer
[in] delay the number of ticks before the operation timeouts, the special values are handled as follow:
TIME_INFINITE is allowed but interpreted as a normal time specification.
TIME_IMMEDIATE this value is not allowed.
[in] vtfunc the timer callback function. After invoking the callback the timer is disabled and the structure can be disposed or reused.
[in] par a parameter that will be passed to the callback function
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 649 of file chvt.h.
References chSysLock(), chSysUnlock(), and chVTSetI().
static void chVTDoTickI (void) inline static
Virtual timers ticker.
Note
The system lock is released before entering the callback and re-acquired immediately after. It is callback's responsibility to acquire the lock if needed. This is done in order to reduce interrupts jitter when many timers are in use.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 666 of file chvt.h.
References ch, CH_CFG_ST_TIMEDELTA, chDbgAssert, chDbgCheckClassI(), chSysLockFromISR(), chSysUnlockFromISR(), chVTGetSystemTimeX(), ch_virtual_timer::delta, ch_virtual_timer::func, ch_virtual_timers_list::lasttime, ch_virtual_timer::next, ch_virtual_timers_list::next, ch_virtual_timer::par, ch_virtual_timer::prev, ch_virtual_timers_list::systime, and ch_system::vtlist.
Referenced by chSysTimerHandlerI().