ChibiOS/RT: Binary Semaphores
Binary Semaphores
RT Kernel » Synchronization
Detailed Description
Binary semaphores related APIs and services.
Operation mode
Binary semaphores are implemented as a set of inline functions that use the existing counting semaphores primitives. The difference between counting and binary semaphores is that the counter of binary semaphores is not allowed to grow above the value 1. Repeated signal operation are ignored. A binary semaphore can thus have only two defined states:
Taken, when its counter has a value of zero or lower than zero. A negative number represent the number of threads queued on the binary semaphore.
Not taken, when its counter has a value of one.
Binary semaphores are different from mutexes because there is no concept of ownership, a binary semaphore can be taken by a thread and signaled by another thread or an interrupt handler, mutexes can only be taken and released by the same thread. Another difference is that binary semaphores, unlike mutexes, do not implement the priority inheritance protocol.
In order to use the binary semaphores APIs the CH_CFG_USE_SEMAPHORES option must be enabled in chconf.h.
Macros
#define _BSEMAPHORE_DATA(name, taken) {_SEMAPHORE_DATA(name.sem, ((taken) ? 0 : 1))}
Data part of a static semaphore initializer.
#define BSEMAPHORE_DECL(name, taken) binary_semaphore_t name = _BSEMAPHORE_DATA(name, taken)
Static semaphore initializer.
Data Structures
struct binary_semaphore_t
Binary semaphore type.
Functions
static void chBSemObjectInit (binary_semaphore_t *bsp, bool taken)
Initializes a binary semaphore.
static msg_t chBSemWait (binary_semaphore_t *bsp)
Wait operation on the binary semaphore.
static msg_t chBSemWaitS (binary_semaphore_t *bsp)
Wait operation on the binary semaphore.
static msg_t chBSemWaitTimeoutS (binary_semaphore_t *bsp, systime_t time)
Wait operation on the binary semaphore.
static msg_t chBSemWaitTimeout (binary_semaphore_t *bsp, systime_t time)
Wait operation on the binary semaphore.
static void chBSemResetI (binary_semaphore_t *bsp, bool taken)
Reset operation on the binary semaphore.
static void chBSemReset (binary_semaphore_t *bsp, bool taken)
Reset operation on the binary semaphore.
static void chBSemSignalI (binary_semaphore_t *bsp)
Performs a signal operation on a binary semaphore.
static void chBSemSignal (binary_semaphore_t *bsp)
Performs a signal operation on a binary semaphore.
static bool chBSemGetStateI (binary_semaphore_t *bsp)
Returns the binary semaphore current state.
Macro Definition Documentation
#define _BSEMAPHORE_DATA (name, taken) {_SEMAPHORE_DATA(name.sem, ((taken) ? 0 : 1))}
Data part of a static semaphore initializer.
This macro should be used when statically initializing a semaphore that is part of a bigger structure.
Parameters
[in] name the name of the semaphore variable
[in] taken the semaphore initial state
Definition at line 91 of file chbsem.h.
#define BSEMAPHORE_DECL (name, taken) binary_semaphore_t name = _BSEMAPHORE_DATA(name, taken)
Static semaphore initializer.
Statically initialized semaphores require no explicit initialization using chBSemInit().
Parameters
[in] name the name of the semaphore variable
[in] taken the semaphore initial state
Definition at line 102 of file chbsem.h.
Function Documentation
static void chBSemObjectInit (binary_semaphore_t * bsp, bool taken) inline static
Initializes a binary semaphore.
Parameters
[out] bsp pointer to a binary_semaphore_t structure
[in] taken initial state of the binary semaphore:
false, the initial state is not taken.
true, the initial state is taken.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 124 of file chbsem.h.
References chSemObjectInit().
static msg_t chBSemWait (binary_semaphore_t * bsp) inline static
Wait operation on the binary semaphore.
Parameters
[in] bsp pointer to a binary_semaphore_t structure
Returns
A message specifying how the invoking thread has been released from the semaphore.
Return values
MSG_OK if the binary semaphore has been successfully taken.
MSG_RESET if the binary semaphore has been reset using bsemReset().
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 141 of file chbsem.h.
References chSemWait().
static msg_t chBSemWaitS (binary_semaphore_t * bsp) inline static
Wait operation on the binary semaphore.
Parameters
[in] bsp pointer to a binary_semaphore_t structure
Returns
A message specifying how the invoking thread has been released from the semaphore.
Return values
MSG_OK if the binary semaphore has been successfully taken.
MSG_RESET if the binary semaphore has been reset using bsemReset().
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 158 of file chbsem.h.
References chDbgCheckClassS(), and chSemWaitS().
static msg_t chBSemWaitTimeoutS (binary_semaphore_t * bsp, systime_t time) inline static
Wait operation on the binary semaphore.
Parameters
[in] bsp pointer to a binary_semaphore_t structure
[in] time the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns
A message specifying how the invoking thread has been released from the semaphore.
Return values
MSG_OK if the binary semaphore has been successfully taken.
MSG_RESET if the binary semaphore has been reset using bsemReset().
MSG_TIMEOUT if the binary semaphore has not been signaled or reset within the specified timeout.
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 184 of file chbsem.h.
References chDbgCheckClassS(), and chSemWaitTimeoutS().
static msg_t chBSemWaitTimeout (binary_semaphore_t * bsp, systime_t time) inline static
Wait operation on the binary semaphore.
Parameters
[in] bsp pointer to a binary_semaphore_t structure
[in] time the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns
A message specifying how the invoking thread has been released from the semaphore.
Return values
MSG_OK if the binary semaphore has been successfully taken.
MSG_RESET if the binary semaphore has been reset using bsemReset().
MSG_TIMEOUT if the binary semaphore has not been signaled or reset within the specified timeout.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 211 of file chbsem.h.
References chSemWaitTimeout().
static void chBSemResetI (binary_semaphore_t * bsp, bool taken) inline static
Reset operation on the binary semaphore.
Note
The released threads can recognize they were waked up by a reset rather than a signal because the bsemWait() will return MSG_RESET instead of MSG_OK.
This function does not reschedule.
Parameters
[in] bsp pointer to a binary_semaphore_t structure
[in] taken new state of the binary semaphore
false, the new state is not taken.
true, the new state is taken.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 232 of file chbsem.h.
References chDbgCheckClassI(), and chSemResetI().
static void chBSemReset (binary_semaphore_t * bsp, bool taken) inline static
Reset operation on the binary semaphore.
Note
The released threads can recognize they were waked up by a reset rather than a signal because the bsemWait() will return MSG_RESET instead of MSG_OK.
Parameters
[in] bsp pointer to a binary_semaphore_t structure
[in] taken new state of the binary semaphore
false, the new state is not taken.
true, the new state is taken.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 253 of file chbsem.h.
References chSemReset().
static void chBSemSignalI (binary_semaphore_t * bsp) inline static
Performs a signal operation on a binary semaphore.
Note
This function does not reschedule.
Parameters
[in] bsp pointer to a binary_semaphore_t structure
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 266 of file chbsem.h.
References chDbgCheckClassI(), chSemSignalI(), and ch_semaphore::cnt.
Referenced by chBSemSignal().
static void chBSemSignal (binary_semaphore_t * bsp) inline static
Performs a signal operation on a binary semaphore.
Parameters
[in] bsp pointer to a binary_semaphore_t structure
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 282 of file chbsem.h.
References chBSemSignalI(), chSchRescheduleS(), chSysLock(), and chSysUnlock().
static bool chBSemGetStateI (binary_semaphore_t * bsp) inline static
Returns the binary semaphore current state.
Parameters
[in] bsp pointer to a binary_semaphore_t structure
Returns
The binary semaphore current state.
Return values
false if the binary semaphore is not taken.
true if the binary semaphore is taken.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 300 of file chbsem.h.
References chDbgCheckClassI(), and ch_semaphore::cnt.