ChibiOS/RT: Core Memory Manager
Core Memory Manager
RT Kernel » Memory Management
Detailed Description
Core Memory Manager related APIs and services.
Operation mode
The core memory manager is a simplified allocator that only allows to allocate memory blocks without the possibility to free them.
This allocator is meant as a memory blocks provider for the other allocators such as:
C-Runtime allocator (through a compiler specific adapter module).
Heap allocator (see Heaps).
Memory pools allocator (see Memory Pools).
By having a centralized memory provider the various allocators can coexist and share the main memory.
This allocator, alone, is also useful for very simple applications that just require a simple way to get memory blocks.
Precondition
In order to use the core memory manager APIs the CH_CFG_USE_MEMCORE option must be enabled in chconf.h.
Note
Compatible with RT and NIL.
Macros
#define CH_CFG_MEMCORE_SIZE 0
Managed RAM size.
Typedefs
typedef void *(* memgetfunc_t) (size_t size, unsigned align)
Memory get function.
typedef void *(* memgetfunc2_t) (size_t size, unsigned align, size_t offset)
Enhanced memory get function.
Data Structures
struct memcore_t
Type of memory core object.
Functions
void _core_init (void)
Low level memory manager initialization.
void * chCoreAllocAlignedWithOffsetI (size_t size, unsigned align, size_t offset)
Allocates a memory block.
void * chCoreAllocAlignedWithOffset (size_t size, unsigned align, size_t offset)
Allocates a memory block.
size_t chCoreGetStatusX (void)
Core memory status.
static void * chCoreAllocAlignedI (size_t size, unsigned align)
Allocates a memory block.
static void * chCoreAllocAligned (size_t size, unsigned align)
Allocates a memory block.
static void * chCoreAllocI (size_t size)
Allocates a memory block.
static void * chCoreAlloc (size_t size)
Allocates a memory block.
Variables
memcore_t ch_memcore
Memory core descriptor.
Macro Definition Documentation
#define CH_CFG_MEMCORE_SIZE 0
Managed RAM size.
Size of the RAM area to be managed by the OS. If set to zero then the whole available RAM is used. The core memory is made available to the heap allocator and/or can be used directly through the simplified core memory allocator.
Note
In order to let the OS manage the whole RAM the linker script must provide the heap_base and heap_end symbols.
Requires CH_CFG_USE_MEMCORE.
Definition at line 53 of file chmemcore.h.
Typedef Documentation
typedef void*(* memgetfunc_t) (size_t size, unsigned align)
Memory get function.
Definition at line 71 of file chmemcore.h.
typedef void*(* memgetfunc2_t) (size_t size, unsigned align, size_t offset)
Enhanced memory get function.
Definition at line 76 of file chmemcore.h.
Function Documentation
void _core_init (void)
Low level memory manager initialization.
Function Class:
Not an API, this function is for internal use only.
Definition at line 81 of file chmemcore.c.
References CH_CFG_MEMCORE_SIZE, memcore_t::endmem, and memcore_t::nextmem.
Referenced by chSysInit().
void * chCoreAllocAlignedWithOffsetI (size_t size, unsigned align, size_t offset)
Allocates a memory block.
This function allocates a block of offset + size bytes. The returned pointer has offset bytes before its address and size bytes after.
Parameters
[in] size the size of the block to be allocated.
[in] align desired memory alignment
[in] offset aligned pointer offset
Returns
A pointer to the allocated memory block.
Return values
NULL allocation failed, core memory exhausted.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 112 of file chmemcore.c.
References chDbgCheck, chDbgCheckClassI(), memcore_t::endmem, MEM_ALIGN_NEXT, MEM_IS_VALID_ALIGNMENT, and memcore_t::nextmem.
Referenced by chCoreAllocAligned(), chCoreAllocAlignedI(), chCoreAllocAlignedWithOffset(), and chCoreAllocI().
void * chCoreAllocAlignedWithOffset (size_t size, unsigned align, size_t offset)
Allocates a memory block.
This function allocates a block of offset + size bytes. The returned pointer has offset bytes before its address and size bytes after.
Parameters
[in] size the size of the block to be allocated.
[in] align desired memory alignment
[in] offset aligned pointer offset
Returns
A pointer to the allocated memory block.
Return values
NULL allocation failed, core memory exhausted.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 148 of file chmemcore.c.
References chCoreAllocAlignedWithOffsetI(), chSysLock(), and chSysUnlock().
Referenced by _heap_init(), and chCoreAlloc().
size_t chCoreGetStatusX (void)
Core memory status.
Returns
The size, in bytes, of the free core memory.
Function Class:
This is an X-Class API, this function can be invoked from any context.
Definition at line 167 of file chmemcore.c.
References memcore_t::endmem, and memcore_t::nextmem.
static void* chCoreAllocAlignedI (size_t size, unsigned align) inline static
Allocates a memory block.
The allocated block is guaranteed to be properly aligned to the specified alignment.
Parameters
[in] size the size of the block to be allocated.
[in] align desired memory alignment
Returns
A pointer to the allocated memory block.
Return values
NULL allocation failed, core memory exhausted.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 135 of file chmemcore.h.
References chCoreAllocAlignedWithOffsetI().
static void* chCoreAllocAligned (size_t size, unsigned align) inline static
Allocates a memory block.
The allocated block is guaranteed to be properly aligned to the specified alignment.
Parameters
[in] size the size of the block to be allocated
[in] align desired memory alignment
Returns
A pointer to the allocated memory block.
Return values
NULL allocation failed, core memory exhausted.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 152 of file chmemcore.h.
References chCoreAllocAlignedWithOffsetI(), chSysLock(), and chSysUnlock().
static void* chCoreAllocI (size_t size) inline static
Allocates a memory block.
The allocated block is guaranteed to be properly aligned for a pointer data type.
Parameters
[in] size the size of the block to be allocated.
Returns
A pointer to the allocated memory block.
Return values
NULL allocation failed, core memory exhausted.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 173 of file chmemcore.h.
References chCoreAllocAlignedWithOffsetI().
static void* chCoreAlloc (size_t size) inline static
Allocates a memory block.
The allocated block is guaranteed to be properly aligned for a pointer data type.
Parameters
[in] size the size of the block to be allocated.
Returns
A pointer to the allocated memory block.
Return values
NULL allocation failed, core memory exhausted.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 189 of file chmemcore.h.
References chCoreAllocAlignedWithOffset().
Variable Documentation
memcore_t ch_memcore
Memory core descriptor.
Definition at line 58 of file chmemcore.c.